### ISSUE TITLE
Copy to clipboard doesn't respect fullPath setting

### ISSUE THREAD

**Issue by sporto** [RoscoP/ActiveFileInStatusBar#1]
Hi, first thanks for this extension

When I set `"ActiveFileInStatusBar.fullpath": false`, the extension shows the relatitve path, but when I click the copy icon it copies the full path into the clipboard. I expect to copy the relative path as well.

Thanks

**Comment by RoscoP** [comment]
I have investigated this a little further, and I don't see any exposure in the vscode API that gives access to the clipboard.  There are a couple NodeJS libs out there, but they end up calling external applications to manipulate the clipboard.  I don't think I'm going to fix this at this time, I would much rather gain access to the clipboard via the vscode API; I might put in a request and will update this if I do.

**Comment by Tyriar** [comment]
This is desirable imo, my main use case for copying a path would be to reference it in a terminal or file explorer. A relative path can only be used in the former, provided that the terminal is in the open folder's directory.

**Comment by spicybackend** [comment]
My exact use case is of the above - I'd love to be able to just use a relative path in a terminal already open in the working directory. How would something like including clipboard.js be for a clean and simple solution?

**Comment by Tyriar** [comment]
@NoodleChump Is this some program where you need the relative path or something? Most programs allow both relative and absolute.

**Comment by spicybackend** [comment]
@Tyriar It's a small JS lib to give clipboard access. As @RoscoP explained, it's not actually possible to copy to the clipboard through the VS Code API, and the current solution to copy the absolute path to the open file is a VS Code action itself. Including a library for clipboard access seems the only way to be able to copy the relative path, or anything else, to the clipboard.

**Comment by Tyriar** [comment]
@NoodleChump oh I mean what's you're use case for needing the relative path?

**Comment by spicybackend** [comment]
@Tyriar It's just a lot nicer not having a massive path pasted into a terminal that's in the working directory

**Comment by RoscoP** [comment]
I'll snoop around the VSC issues and see if they are open to providing an API to the clipboard.  I kind of assumed they would've made one by now.

**Comment by RoscoP** [comment]
Put in an [issue/request 10933](https://github.com/Microsoft/vscode/issues/10933) for VSCode API - we'll see what they say.

**Comment by leocaseiro** [comment]
The extension https://marketplace.visualstudio.com/items?itemName=bgse.relative-path-and-line helps with that 😄
