### ISSUE TITLE
[Cosmetics] Drive letter in lowercase and no ActiveFileInStatusBar icon in the status bar

### ISSUE THREAD

**Issue by DoCode** [RoscoP/ActiveFileInStatusBar#10]
1. The drive letter is in lowercase on Windows 10 (Linux/Mac not tested!)
2. Doesn't show th following plugin icon on the file path  
![ActiveFileInStatusBar icon](https://raw.githubusercontent.com/RoscoP/ActiveFileInStatusBar/master/media/icon.png)

**Comment by RoscoP** [comment]
Icon was removed in the latest version.  Drive letter is whatever the system gives back to me.  I'll think about adding changing it next time I'm in the code, but going to close this for now.
