### ISSUE TITLE
Change config properties to be lower case

### ISSUE THREAD

**Issue by Tyriar** [RoscoP/ActiveFileInStatusBar#3]
Lower case is the is the standard for vscode, it looks ugly with this casing:

![image](https://cloud.githubusercontent.com/assets/2193314/16542925/563dd2c8-4071-11e6-933a-aa7dbea03475.png)

**Comment by RoscoP** [comment]
I tried to work this a little bit, but it became problematic to track which set of settings the user had set and which ones were the defaults with the new lower case.  Ultimately I decided to keep it the same to keep everyone's existing settings the same and reduce the logic about trying to get their settings correct
