### ISSUE TITLE
Add an option to show the project folder at the start of the file path

### ISSUE THREAD

**Issue by AlejandroC90** [RoscoP/ActiveFileInStatusBar#9]
Thanks for the extension, it's pretty useful!
I would like to have and option that Instead of showing the full path
![image](https://user-images.githubusercontent.com/5132907/31386710-5f083ea4-ad8d-11e7-8ca7-97dc733d47e3.png)

Show just the path within the project folder, like this:
_Proyecto 2/perfil_proveedor.php_

To save some space in the status bar o sometimes you just care about the path within the project,

**Comment by RoscoP** [comment]
Then I have the option for you!
`"ActiveFileInStatusBar.fullpath": false`
